name: Deploy nice stay app

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build Docker image
      run: docker build . -t ${{secrets.DOCKERHUB_USERNAME}}/nice_stay:latest


    - name: Docker push
      env:
        REPO: nice_stay
      run:
        docker push ${{secrets.DOCKERHUB_USERNAME}}/$REPO

    - name: Docker Pull and Docker compose
      env:
          REPO: nice_stay
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        port: ${{secrets.PORT}}
        key: ${{secrets.KEY}}
        script:
          # cat ~/DOCKERHUB_pas.txt | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
          # docker pull ${{secrets.DOCKERHUB_USERNAME}}/$REPO
          cd /home/ec2-user/Nice_stay
          docker run --network my-net --name stylish -p 3000:3000 --env-file .env -d kellychen8411/nice_stay

    

    