name: Test nice stay app

on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: install docker
        uses: docker-practice/actions-setup-docker@master
      
      - name: check docker version
        run: docker version
      
      - name: pull mysql docker image
        run: docker pull mysql:8
      
      - name: docker run mysql
        run: docker run --name mysql-con -p 3306:3306 -d -e MYSQL_ROOT_PASSWORD=${{secrets.DB_PASSWORD_TEST_NEW}} mysql:8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install mocha globally
        run: npm install -g mocha

      - name: Install package
        run: npm install

      - name: "Run Test"
        run: NODE_ENV=test API_VERSION=1.0 DB_HOST_TEST_NEW=${{secrets.DB_HOST_TEST_NEW}} DB_USER_TEST_NEW=${{secrets.DB_USER_TEST_NEW}} DB_PASSWORD_TEST_NEW=${{secrets.DB_PASSWORD_TEST_NEW}} DB_DATABASE_TEST_NEW=${{secrets.DB_DATABASE_TEST_NEW}} CLOUDFRONT_DOMAIN=${{secrets.CLOUDFRONT_DOMAIN}} mocha --timeout 10000 --exit

